行列積
A
=
⎡
⎢
⎣
−
1
2
3
4
−
5
6


7
8
−
9
⎤
⎥
⎦
,
B
=
⎡
⎢
⎣
0
2
1
0
2
−
8
2
9
−
1
⎤
⎥
⎦

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

行列の積の手計算
https://atarimae.biz/archives/23930
6	29	-20
12	52	38
-18	-51	-48

https://slack-redir.net/link?url=https%3A%2F%2Feasy-copy-mathjax.xxxx7.com%2F

$$
AB= 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$

【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。
numpy.matmul — NumPy v1.16 Manual
numpy.dot — NumPy v1.16 Manual
《3種類の違い》
np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。
今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

https://note.nkmk.me/python-numpy-matrix/

SyntaxError: invalid syntax (<ipython-input-1-c0e0d6e20e9f>, line 1)

In [10]:
c_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)
print("行列積AB np.matmul()の結果\n{}".format(c_ndarray_matmul))

c_ndarray_dot = np.dot(a_ndarray, b_ndarray)
print("行列積AB np.dotl()の結果\n{}".format(c_ndarray_dot))

#@が使い勝手良い
c_ndarray_at=a_ndarray@b_ndarray
print("行列積AB @の結果\n{}".format(c_ndarray_at))

行列積AB np.matmul()の結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
行列積AB np.dotl()の結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
行列積AB @の結果
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
それらの値を全て足し合わせる



３次元だと挙動が変わる
線形写像が行列積で求める。

NumPyでまとめて計算、for分で要素を取り出す

In [28]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#a_ndarrayの0行目とb_ndarrayの0列目をそれぞれ積、答えをsum()する
mul00=(a_ndarray[:1]*b_ndarray[:, 0]).sum()
print("Aの0行目とBの0列目: {}".format(mul00))

Aの0行目とBの0列目: 6


In [30]:
#b_ndarray[:, 0]

In [40]:
a_ndarray.shape

(3, 3)

In [42]:
#for文、要素を一つずつ取り出して、掛け算して加算していく

mul00=0

for i in range(a_ndarray.shape[1]):
    mul00 +=a_ndarray[0,i]*b_ndarray[i,0]
#aの0行目を取り出す、bの0列目を取り出す

print("Aの0行目とBの0列目: {}".format(mul00))

Aの0行目とBの0列目: 6


【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。
計算結果である 
3
×
3
 の行列Cの各要素 
c
i
,
j
 は数式で表すと次のようになります。
c
i
,
j
=
2
∑
k
=
0
 
a
i
,
k
b
k
,
j
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス 
i
 や 
j
 を1増やすと、次の行や列に移ることができます。

In [46]:
def matrix_product_for(a,b):
    c=np.empty((a.shape[0], b.shape[1]))
    
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i,j] =(a[i]*b[:,j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("結果: {}".format(matrix_product_for(a_ndarray, b_ndarray)))

結果: [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [62]:
#ブロードキャスト　要素数が足りない場合には自動で行・列を拡張してくれる機能
def matrix_product_broadcast(a,b):
    c=(a[:, np.newaxis, :]*b.T).sum(axis=2)
    
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("結果: {}".format(matrix_product_broadcast(a_ndarray, b_ndarray)))

結果: [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [68]:
def matrix_product_broadcast(a,b):
    c=(a[:, np.newaxis, :]*b.T).sum(axis=2)
    
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("Aに新たな次元を追加\n{}".format(a_ndarray[:, np.newaxis, :]))
a=a_ndarray[:, np.newaxis, :]
print(a[2][0][2])#奥に2、0行目、2列目
print(a_ndarray[:, np.newaxis, :].shape)
#[]によるインデックスの中でnp.newaxisを使うとその位置にサイズが1の新たな次元が追加される。
print("Bを転置\n{}".format(b_ndarray.T))
print("A(3,1,3)と転置Bを掛け合わせる\n{}".format(a_ndarray.reshape(3,1,3)*b_ndarray.T))
#(3,3,3)にブロードキャストされる
print("axis=2(奥行き)で合計する\n{}".format((a_ndarray.reshape(3,1,3)*b_ndarray.T).sum(axis=2)))

Aに新たな次元を追加
[[[-1  2  3]]

 [[ 4 -5  6]]

 [[ 7  8 -9]]]
-9
(3, 1, 3)
Bを転置
[[ 0  0  2]
 [ 2  2  9]
 [ 1 -8 -1]]
A(3,1,3)と転置Bを掛け合わせる
[[[  0   0   6]
  [ -2   4  27]
  [ -1 -16  -3]]

 [[  0   0  12]
  [  8 -10  54]
  [  4  40  -6]]

 [[  0   0 -18]
  [ 14  16 -81]
  [  7 -64   9]]]
axis=2(奥行き)で合計する
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。
・列数と行数が等しい時に定義されている。
・a.shape[1]==b.shape[0]の場合のみ計算を行う、そうでない場合は不適切であることを説明する。
shapeの(x.y)と(v,w)の時、y（列数）とw(行数)

optionキーを押しながら、¥キー：\

$$ D = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6
    \end{array}
  \right],
  E- = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4
    \end{array}
  \right] $$


In [ ]:
d_ndarray= np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [75]:
# if文

def matrix_product_broadcast(a,b):
    c=np.empty((a.shape[0], b.shape[1]))
    
    if a.shape[1]==b.shape[0]:
        c=(a[:, np.newaxis, :]*b.T).sum(axis=2)
        return c
    else:
        print("a.shape[1]!=b.shape[0]: {}!={}".format(a.shape[1],b.shape[0]))
        return None
    

d_ndarray= np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print("結果: {}".format(matrix_product_broadcast(d_ndarray,e_ndarray)))

a.shape[1]!=b.shape[0]: 3!=2
結果: None


In [78]:
# assert　assert 条件式, 条件式がFalseの場合に出力するメッセージ
#、バグと呼ばれるプログラムや関数の間違いを見つけ、それらを排除する作業のため
def matrix_product_broadcast(a,b):
    c=np.empty((a.shape[0], b.shape[1]))
    
    assert a.shape[1]==b.shape[0],"a.shape[1]!=b.shape[0]: {}!={}".format(a.shape[1],b.shape[0])
    c=(a[:, np.newaxis, :]*b.T).sum(axis=2)
    return c

d_ndarray= np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print("結果: {}".format(matrix_product_broadcast(d_ndarray,e_ndarray)))

AssertionError: a.shape[1]!=b.shape[0]: 3!=2

【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。
numpy.transpose — NumPy v1.16 Manual
numpy.ndarray.T — NumPy v1.16 Manual


In [81]:
d_ndarray= np.array([[-1, 2, 3], [4, -5, 6]])
d_T=d_ndarray.T
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
e_T=e_ndarray.T

print("D転置の計算結果:\n{}".format(d_T@e_ndarray))

print("E転置の計算結果:\n{}".format(d_ndarray@e_T))

D転置の計算結果:
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
E転置の計算結果:
[[ 46  -4]
 [-34  73]]
